MACHINE Test
//INCLUDE "inc/Test02.bs";
ATTRIBUTES
	#define PI 3.14159
	#define ONE_CIR 2 * PI
	#define HALF_CIR PI
	#define DEG_PI 180

	int global_int;
	
	typedef struct {
		int id_0;
		int id_1; 
	}u_tuple;
	
	const int pi = HALF_CIR;
OPERATIONS
	int math_func(int arg1, int arg2){
		int ret;
		ret = arg1 * arg2 + arg1 / arg2;
		return ret;
	}

	int if_func(int cdt, int arg1){
		int ret;
		if(cdt > 1){
			ret = arg1 + 1;			
		}
		else{
			ret = arg1 - 1;
		}
		
		if(cdt == 10){
			ret = ret * 10;
		}
		return ret;
	}
	
	void main(){
		int v1,v2;
		v1 = math_func(2, 2);
		v2 = if_func(9, 5);
	}
END